#!/usr/bin/env python3
"""
review_image.py — Review of an image generated by a vision model (OpenRouter).

Sends the image (base64-encoded, read from disk) to a VISION model
(`google/gemma-4-31b-it` by default — good and inexpensive) with a critique prompt, and returns
the reviewer's textual verdict. Serves the "never post without review" workflow
from SKILL.md (score ≥ 8/10 → keep; < 6/10 → regenerate).

Like gen_image.py:
  - the key comes from the environment (`OPENROUTER_API_KEY`), never from an argument;
  - the base64 image (>2 MB) is NEVER passed as a shell argument: it is posted
    in the request body read from the socket;
  - retries on transient errors (429/5xx/network).

Usage:
  python3 review_image.py --image IMG.png --criteres "Portrait crayonné d'Oscar, …"
  python3 review_image.py --image IMG.png --criteres-file crit.txt --model google/gemma-4-31b-it --json

Exit codes:
  0  review obtained (verdict text on stdout)
  1  failure (HTTP / network / empty response)
  2  usage (missing key, image not found, empty criteria)
"""
import sys
import os
import re
import json
import time
import base64
import argparse
import urllib.request
import urllib.error

API_URL = "https://openrouter.ai/api/v1/chat/completions"
DEFAULT_VISION_MODEL = "google/gemma-4-31b-it"  # inexpensive vision model; avoid Gemini (project preference)

CONSIGNE = (
    "Tu es critique d'illustration pour un jeu de rôle. Évalue l'image fournie sur 4 axes "
    "(Style, Description respectée, Qualité/anatomie, absence de texte parasite), donne une "
    "note /10 par axe puis une note globale /10, et liste les défauts concrets à corriger.\n"
    "IMPÉRATIF — termine ta réponse par EXACTEMENT ces deux lignes, sans rien après :\n"
    "NOTE_GLOBALE: <N>/10   (N = nombre entre 0 et 10, décimales autorisées)\n"
    "CORRECTIONS: <consignes brèves et concrètes pour régénérer, sur une seule ligne, ou \"aucune\">\n"
    "Contexte et critères attendus :\n"
)


def die(msg, code):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(code)


def call_api(payload, api_key, retries, timeout):
    body = json.dumps(payload).encode()
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    last_err = None
    for attempt in range(1, retries + 2):
        try:
            req = urllib.request.Request(API_URL, data=body, headers=headers)
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return json.load(r)
        except urllib.error.HTTPError as e:
            last_err = f"HTTP {e.code}: {e.read().decode(errors='replace')[:500]}"
            if not (e.code == 429 or 500 <= e.code < 600):
                raise RuntimeError(last_err)
        except (urllib.error.URLError, TimeoutError, OSError) as e:
            last_err = f"network: {e}"
        if attempt <= retries:
            time.sleep(2 ** (attempt - 1))
    raise RuntimeError(last_err or "unknown failure")


def parse_score(verdict):
    """Extracts the overall score from the verdict. Returns a float 0–10 or None if absent.
    Looks first for the machine line `NOTE_GLOBALE: N/10`, then a 'globale … N/10' mention,
    then the last `N/10` encountered."""
    m = re.search(r"NOTE_GLOBALE\s*:?\s*([0-9]+(?:[.,][0-9]+)?)\s*/\s*10", verdict, re.I)
    if not m:
        m = re.search(r"global[ea]?\D{0,20}([0-9]+(?:[.,][0-9]+)?)\s*/\s*10", verdict, re.I)
    if not m:
        allm = re.findall(r"([0-9]+(?:[.,][0-9]+)?)\s*/\s*10", verdict)
        if allm:
            try:
                return float(allm[-1].replace(",", "."))
            except ValueError:
                return None
        return None
    try:
        return float(m.group(1).replace(",", "."))
    except ValueError:
        return None


def parse_corrections(verdict):
    """Extracts the correction instruction (line `CORRECTIONS: …`). Returns '' if absent or 'aucune'."""
    m = re.search(r"CORRECTIONS\s*:?\s*(.+)", verdict, re.I)
    if not m:
        return ""
    corr = m.group(1).strip().strip('"').strip()
    return "" if corr.lower() in ("aucune", "none", "n/a", "-", "") else corr


def review(image_path, criteres, api_key, model=DEFAULT_VISION_MODEL, retries=2, timeout=90):
    """Evaluates an image via a vision model. Returns the verdict text.
    Raises RuntimeError (network/HTTP/empty) or OSError (unreadable image).
    Reusable by the generate_reviewed.py wrapper."""
    with open(image_path, "rb") as f:
        img_b64 = base64.b64encode(f.read()).decode()
    ext = os.path.splitext(image_path)[1].lower().lstrip(".") or "png"
    mime = "jpeg" if ext in ("jpg", "jpeg") else ext
    payload = {
        "model": model,
        "messages": [{
            "role": "user",
            "content": [
                {"type": "text", "text": CONSIGNE + criteres},
                {"type": "image_url",
                 "image_url": {"url": f"data:image/{mime};base64,{img_b64}"}},
            ],
        }],
    }
    data = call_api(payload, api_key, retries, timeout)
    if isinstance(data, dict) and "error" in data:
        raise RuntimeError(f"API: {json.dumps(data['error'])[:500]}")
    verdict = ((data.get("choices") or [{}])[0].get("message", {}) or {}).get("content", "")
    verdict = (verdict or "").strip()
    if not verdict:
        raise RuntimeError("empty verdict returned by the vision model.")
    return verdict


def main():
    p = argparse.ArgumentParser(
        description="Review of an image via an OpenRouter vision model.",
        formatter_class=argparse.RawDescriptionHelpFormatter, epilog=__doc__)
    p.add_argument("--image", required=True, help="Path to the PNG/JPEG to evaluate.")
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--criteres", help="Expected criteria (description, posture, atmosphere…).")
    g.add_argument("--criteres-file", help="Criteria file, or '-' for stdin.")
    p.add_argument("--model", default=DEFAULT_VISION_MODEL, help=f"Vision model (default {DEFAULT_VISION_MODEL}).")
    p.add_argument("--retries", type=int, default=2, help="Transient retries (default 2).")
    p.add_argument("--timeout", type=int, default=90, help="HTTP timeout in seconds (default 90).")
    p.add_argument("--json", action="store_true", dest="as_json", help="Machine-readable output.")
    args = p.parse_args()

    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        die("OPENROUTER_API_KEY not set in the environment.", 2)

    if args.criteres_file == "-":
        criteres = sys.stdin.read().strip()
    elif args.criteres_file:
        try:
            with open(args.criteres_file) as f:
                criteres = f.read().strip()
        except OSError as e:
            die(f"reading criteria file: {e}", 2)
    else:
        criteres = args.criteres.strip()
    if not criteres:
        die("empty criteria.", 2)

    try:
        verdict = review(args.image, criteres, api_key, args.model, args.retries, args.timeout)
    except OSError as e:
        die(f"reading image file: {e}", 2)
    except RuntimeError as e:
        die(str(e), 1)

    if args.as_json:
        print(json.dumps({"ok": True, "image": args.image, "model": args.model,
                          "score": parse_score(verdict), "corrections": parse_corrections(verdict),
                          "verdict": verdict}, ensure_ascii=False))
    else:
        print(verdict)
    sys.exit(0)


if __name__ == "__main__":
    main()
